# configs/detector_config.yaml
model:
  type: "YOLOv8"
  weights: "yolov8l.pt"  # Will be downloaded automatically
  confidence_threshold: 0.5
  iou_threshold: 0.45
  device: "0"  # Use "0" for first GPU, "cpu" for CPU

classes:
  # COCO class indices (garbage truck could be mapped to truck class 7)
  target_classes: [7]  # 7 is truck in COCO dataset
  custom_mapping:
    7: "truck"  # Map COCO truck class to garbage truck